### ISSUE TITLE
Neither the credentials or download process initialized!  (Again)

### ISSUE THREAD

**Issue by Mikester-Calgary** [hdus/SRTM-Downloader#16]
This is a reoccurrence of an old issue.
NASA's data service appears to be up again but is not able to be accessed/downloaded by the SRTM QGIS plugin.
-The plugin itself seems to run fine.
-No credential page is offered after selection of extent area.
-No images are downloaded.

**Comment by jameshgrn** [comment]
I am also having this problem with QGIS 3.14. Running a Mac OS on Big Sur. The credentials page doesn't pop up

**Comment by hdus** [comment]
NASA has changed the download URL. It's fixed with release 3.1.10.

**Comment by PeterSprague** [comment]
Seems like 3.1.10 has not fixed this.  Same issue for me today

**Comment by hdus** [comment]
I can't reproduce the issue. For me it works fine.
